version: "3.10"

services:
  clkr-service:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ~/prod/nginx/staticfiles/clkr/static:/src/static
      - ~/prod/clkr/src/logs/:/src/logs
    environment:
      - LOG_FILE=/src/logs/
    env_file:
      - .env
    expose:
      - 8000
    command: sh -c "uvicorn clkr_core.asgi:app --proxy-headers --host 0.0.0.0 --port 8000"
    depends_on:
      - clkr-postgresql
      - clkr-redis

  clkr-postgresql:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ~/prod/clkr/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  clkr-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ~/prod/clkr/redis-data/data:/data
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"

  clkr-worker:
    hostname: clkr-worker
    restart: unless-stopped
    build:
      context: .
    command: sh -c "celery -A clkr_core worker -c 1 -l INFO"
    environment:
      - LOG_FILE=/src/logs/worker/
    env_file:
      - .env
    volumes:
      - ~/prod/clkr/src/logs/worker/:/src/logs/worker
    links:
      - clkr-redis
    depends_on:
      - clkr-redis

  clkr-certbot:
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ~/prod/nginx/certbot/conf/clkr:/etc/letsencrypt
      - ~/prod/nginx/certbot/www/clkr:/var/www/certbot
