version: "3.10"

services:
  clkr-service:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ~/prod/nginx/staticfiles/clkr/static:/src/static
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - clkr-postgresql
      - clkr-redis

  clkr-postgresql:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ~/prod/clkr/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  clkr-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ~/prod/clkr/redis-data/data:/data
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    
  clkr-certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ~/prod/nginx/certbot/conf/clkr:/etc/letsencrypt
      - ~/prod/nginx/certbot/www/clkr:/var/www/certbot
