version: "3.10"

services:
  clkr-service:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ~/prod/nginx/staticfiles/clkr/static:~/src/static
    env_file:
      - .env
    depends_on:
      - clkr-postgresql
      - clkr-redis

  clkr-postgresql:
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      - ~/prod/clkr/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=hGTg#43GR543F&ygkj*hGfDDrf?
      - POSTGRES_DB=clkr
    # env_file:
    #   - .env
    ports:
      - 127.0.0.3:5432:5432

  clkr-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - ~/prod/clkr/redis-data/data:/data
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    
  clkr-certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ~/prod/nginx/certbot/conf/clkr:/etc/letsencrypt
      - ~/prod/nginx/certbot/www/clkr:/var/www/certbot
