
version: "3.10"

services:
  clkr-service:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ~/prod/nginx/staticfiles/clkr/static:~/src/static
    env_file:
      - ./.env
  postgresql-db:
    restart: unless-stopped
    image: postgres
    volumes:
      - ~/prod/clkr/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=hGTg#43GR543F&ygkj*hGfDDrf?
      - POSTGRES_DB=clkr
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ~/prod/clkr/redis-data/data:/data
    env_file:
      - ./.env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ~/prod/nginx/certbot/conf/clkr:/etc/letsencrypt
      - ~/prod/nginx/certbot/www/clkr:/var/www/certbot
