version: "3.10"

services:
  nginx:
    restart: unless-stopped
    build:
        context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/var/www/static
      - ./persistentdata/media:/var/www/media
  clkr-service:
    restart: unless-stopped
    build:
      context: .
    image: clkr-service
    volumes:
      - ./static:/var/www/static
    env_file:
      - ./.env
  postgresql-db:
    restart: unless-stopped
    image: postgres
    volumes:
            - ./persistentdata/db:/var/lib/postgresql/data
    env_file:
      - ./postgresql-db/.pg-env # why - see the next step
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt # <--here
      - ./persistentdata/certbot/www:/var/www/certbot