# Generated by Django 4.2.3 on 2023-08-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_token_tokenproxy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verify',
            new_name='verified',
        ),
    ]
