# Generated by Django 4.1.7 on 2023-03-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('long_link', models.URLField(max_length=30000)),
                ('statistics', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTransitionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_unparsed', models.CharField(max_length=150)),
                ('device', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('ref_link', models.CharField(max_length=30000)),
                ('user_ip', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cutter.linkmodel')),
            ],
        ),
    ]
