# Generated by Django 4.1.7 on 2023-03-30 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('long_link', models.URLField(max_length=30000)),
                ('statistics', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('svg_image', models.CharField(max_length=30)),
                ('png_image', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_expire', models.DateField()),
                ('use_alias', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.grouplinkmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTransitionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_unparsed', models.CharField(max_length=150)),
                ('device', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('ref_link', models.CharField(max_length=30000)),
                ('user_ip', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.linkmodel')),
            ],
        ),
    ]
