# Generated by Django 4.2.2 on 2023-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
