# Generated by Django 4.2.2 on 2023-06-07 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_model', '0003_alter_linkmodel_date_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
