# Generated by Django 4.2.2 on 2023-06-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0005_alter_linkmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
