# Generated by Django 4.2.2 on 2023-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0006_alter_linkmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='png_image',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='svg_image',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
