# Generated by Django 4.2.2 on 2023-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0007_alter_linkmodel_png_image_alter_linkmodel_svg_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkTransitionsModel',
            new_name='StatisticsModel',
        ),
        migrations.RenameField(
            model_name='grouplinkmodel',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='password',
            field=models.CharField(max_length=1024),
        ),
    ]
