# Generated by Django 4.2.2 on 2023-06-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0010_groupstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstatistics',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_model.linkmodel'),
        ),
    ]
