# Generated by Django 4.2.2 on 2023-06-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0012_alter_groupstatistics_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstatistics',
            name='group',
        ),
        migrations.RemoveField(
            model_name='linkstatistics',
            name='link',
        ),
        migrations.DeleteModel(
            name='AccountStatistics',
        ),
        migrations.DeleteModel(
            name='GroupStatistics',
        ),
        migrations.DeleteModel(
            name='LinkStatistics',
        ),
    ]
