# Generated by Django 4.2.2 on 2023-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0013_remove_groupstatistics_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='statistics',
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='browser',
            field=models.CharField(default='Not defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='device',
            field=models.CharField(default='Not defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='os',
            field=models.CharField(default='Not defined', max_length=20),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='ref_link',
            field=models.CharField(default='Not defined', max_length=30000),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='user_agent_unparsed',
            field=models.CharField(default='Not defined', max_length=150),
        ),
    ]
