# Generated by Django 4.2.2 on 2023-07-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0014_remove_linkmodel_statistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='png_image',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='svg_image',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='use_alias',
        ),
    ]
