# Generated by Django 4.2.2 on 2023-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0015_remove_linkmodel_png_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplinkmodel',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='is_private',
        ),
        migrations.AddField(
            model_name='grouplinkmodel',
            name='rotation',
            field=models.BooleanField(default=False),
        ),
    ]
