# Generated by Django 4.2.2 on 2023-07-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_model', '0016_remove_grouplinkmodel_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplinkmodel',
            name='alias',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='db_model.grouplinkmodel'),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='grouplinkmodel',
            unique_together={('user', 'title')},
        ),
    ]
