# Generated by Django 4.2.2 on 2023-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0017_grouplinkmodel_alias_alter_linkmodel_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
