# Generated by Django 4.2.2 on 2023-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0018_alter_grouplinkmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
