# Generated by Django 4.2.2 on 2023-07-06 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_model', '0019_alter_grouplinkmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='password',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
