# Generated by Django 4.2.2 on 2023-07-17 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_model', '0020_alter_grouplinkmodel_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='links', to='db_model.grouplinkmodel'),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
