# Generated by Django 4.2.2 on 2023-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0022_grouplinkmodel_date_expire_alter_linkmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
