# Generated by Django 4.2.2 on 2023-07-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0023_alter_linkmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='alias',
            field=models.SlugField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.grouplinkmodel'),
        ),
    ]
