# Generated by Django 4.2.2 on 2023-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0024_alter_grouplinkmodel_alias_alter_linkmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
