# Generated by Django 4.2.2 on 2023-07-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0025_linkmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplinkmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
