# Generated by Django 4.2.2 on 2023-07-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0026_grouplinkmodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsmodel',
            name='fingerprint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='db_model.linkmodel'),
        ),
    ]
