# Generated by Django 4.2.2 on 2023-07-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0027_statisticsmodel_fingerprint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplinkmodel',
            old_name='alias',
            new_name='slug',
        ),
    ]
