# Generated by Django 4.2.3 on 2023-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0029_alter_linkmodel_group_alter_linkmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='password',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
