# Generated by Django 4.2.3 on 2023-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0032_alter_linkmodel_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statisticsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
