# Generated by Django 4.2.3 on 2023-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0033_alter_grouplinkmodel_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
