# Generated by Django 4.2.3 on 2023-08-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0035_alter_linkmodel_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
