# Generated by Django 4.2.3 on 2023-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0036_alter_linkmodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
