# Generated by Django 4.2.3 on 2023-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0038_userinfomodel_alter_linkmodel_password_qrcodemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
