# Generated by Django 4.2.3 on 2023-08-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0039_qrcodemodel_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouplinkmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='linkmodel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='grouplinkmodel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
