# Generated by Django 4.2.3 on 2023-08-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0040_remove_grouplinkmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='grouplinkmodel',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
