# Generated by Django 4.2.3 on 2023-09-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0042_alter_linkmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_model.grouplinkmodel'),
        ),
    ]
