# Generated by Django 4.2.3 on 2023-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0043_alter_linkmodel_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmodel',
            name='unauth_ralation',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
