# Generated by Django 4.2.3 on 2023-09-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_model', '0044_linkmodel_unauth_ralation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkmodel',
            old_name='unauth_ralation',
            new_name='unauth_relation',
        ),
    ]
